version: '3'
services:
  web:
    container_name: php-book-app-web
    build:
      context: .
      dockerfile: ./Docker/php/Dockerfile
    volumes:
      - .:/var/www/html:cached
    environment:
      - APP_DEFAULT_LOCALE=ja_JP
      - APP_DEFAULT_TIMEZONE=Asia/Tokyo
      - DATABASE_HOST=php-book-app-db
      - DATABASE_USER=root
      - DATABASE_PASS=secret
      - DATABASE_NAME=qa_app
      - DATABASE_TEST_URL=mysql://root:secret@php-book-app-db/test
    command: bash -c "sh docker-init-setup.sh && apache2-foreground"
    ports:
      - "5000:80"
  db:
    container_name: php-book-app-db
    build:
      context: .
      dockerfile: ./Docker/mysql/Dockerfile
    volumes:
      - ./Docker/mysql/sqls:/docker-entrypoint-initdb.d
      - ./Docker/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - "13306:3306"